version: '3.8'

services:
  # API Gateway
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-sua_chave_secreta_muito_segura_aqui}
      - AUTH_SERVICE_PORT=3001
      - PRODUCTS_SERVICE_PORT=3002
      - EXTERNAL_API_URL=https://fakestoreapi.com
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    depends_on:
      - auth-service
      - products-service
    networks:
      - api-network
    restart: unless-stopped

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_PORT=3001
      - JWT_SECRET=${JWT_SECRET:-sua_chave_secreta_muito_segura_aqui}
      - JWT_EXPIRES_IN=24h
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    command: node services/auth-service/index.js
    networks:
      - api-network
    restart: unless-stopped

  # Products Service
  products-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PRODUCTS_SERVICE_PORT=3002
      - JWT_SECRET=${JWT_SECRET:-sua_chave_secreta_muito_segura_aqui}
      - EXTERNAL_API_URL=https://fakestoreapi.com
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    command: node services/products-service/index.js
    networks:
      - api-network
    restart: unless-stopped

networks:
  api-network:
    driver: bridge 