services:
  - type: web
    name: enterprise-microservices-gateway
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: AUTH_SERVICE_PORT
        value: 3001
      - key: PRODUCTS_SERVICE_PORT
        value: 3002
      - key: EXTERNAL_API_URL
        value: https://fakestoreapi.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
    healthCheckPath: /health
    autoDeploy: true 